dist: trusty
notifications:
  email: false
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# command to build
install:
  # - mvn -U compile > /dev/null || true
  - ./gradlew assemble
  - ./gradlew build
  - ./gradlew jar
  - ./gradlew javadoc
  - ./gradlew releaseProcessingLib -PreleaseVersion=nightly

# command to run tests
script:
  - ./gradlew check

after_success: